# Generated by Django 5.0.6 on 2024-07-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movierelease',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
