# Generated by Django 5.0.6 on 2024-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_post_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ram', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
